PUT http://localhost:5000/api/lists/620fd87946404c103027520d
Content-Type: application/json

{
  "list": {
    "title": "its yours", "position": 1, "boardId": "620e7eacd7c1aa2580b5b791", "cards": []
  }
}
